# Generated by Django 4.1.1 on 2022-10-03 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busbookapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MyModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busbookapp.mymodel')),
            ],
        ),
    ]
