# Generated by Django 4.1.1 on 2022-10-03 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('busbookapp', '0002_mymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='MyModel',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
            preserve_default=False,
        ),
    ]
