# Generated by Django 4.1.1 on 2022-10-03 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busbookapp', '0003_remove_mymodel_mymodel_mymodel_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mymodel',
            options={'ordering': ['group']},
        ),
    ]
