# Generated by Django 4.1.1 on 2022-10-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busbookapp', '0004_alter_mymodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=20)),
                ('bus_no', models.IntegerField()),
                ('start', models.CharField(max_length=30)),
                ('end', models.CharField(max_length=30)),
                ('seats', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='mymodel',
            options={},
        ),
    ]
